repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        name: ruff-check
        args: [--no-fix]
        files: ^track_changes/.*\.py$
      - id: ruff-format
        name: ruff-format
        files: ^track_changes/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^track_changes/.*\.py$