[tool.semantic_release]
commit_parser = "conventional"
version_scheme = "semver"
version_source = "commit"
version_variables = [
  "track_changes/__init__.py:__version__",
  "track_changes/metadata.txt:version"
]
changelog_file = "CHANGELOG.md"
changelog_sections = [
    ["feat", "Features"],
    ["fix", "Bug Fixes"],
    ["perf", "Performance Improvements"],
    ["refactor", "Code Refactoring"],
    ["style", "Code Style"],
    ["test", "Tests"],
    ["build", "Build System"],
    ["ci", "Continuous Integration"],
    ["docs", "Documentation"],
    ["chore", "Chores"]
]

# Configuration for main branch (stable releases)
[tool.semantic_release.branches.main]
match = "main"
prerelease = false
merge_prerelease = true
prerelease_token = "rc"

# Configuration for development branch (prereleases)
[tool.semantic_release.branches.development]
match = "(?!main$).*"
prerelease = true
prerelease_token = "rc"
changelog = false
merge_prerelease = false
