[tool.semantic_release]
commit_parser = "conventional"
version_scheme = "semver"
version_source = "commit"
version_variables = [
  "track_changes/__init__.py:__version__",
  "track_changes/metadata.txt:version"
]
changelog_file = "CHANGELOG.md"
changelog_ignore_patterns = ["^\\d+\\.\\d+\\.\\d+(-rc(\\.\\d+)?|rc\\d*)$"]

# Configuration for main branch (stable releases)
[tool.semantic_release.branches.main]
match = "main"
prerelease = false
merge_prerelease = true

# Configuration for all other branches (prereleases)
[tool.semantic_release.branches."(?!main$).*"]
match = "(?!main$).*"
prerelease = true
changelog = false
