[tool.semantic_release]
commit_parser = "conventional"
version_scheme = "semver"
version_source = "commit"
version_variables = [
  "track_changes/__init__.py:__version__",
  "track_changes/metadata.txt:version"
]
changelog_file = "CHANGELOG.md"
tag_format = "v{version}"
changelog_sections = [
    ["feat", "Features"],
    ["fix", "Bug Fixes"],
    ["perf", "Performance Improvements"],
    ["refactor", "Code Refactoring"],
    ["style", "Code Style"],
    ["test", "Tests"],
    ["build", "Build System"],
    ["ci", "Continuous Integration"],
    ["docs", "Documentation"],
    ["chore", "Chores"]
]

[tool.semantic_release.remote]
token = "GH_TOKEN"

# Configuration for main branch (stable releases)
[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.publish]
upload_to_vcs_release = true
remove_dist = true
