[tool.semantic_release]
commit_parser = "conventional"
version_source = "commit"
changelog_file = "CHANGELOG.md"

# Configuration for main branch
[tool.semantic_release.branches.main]
match = "main"
prerelease = false

# Configuration for all other branches
[tool.semantic_release.branches.default]
match = ".*"
prerelease = true 