# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_changes/ui/about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(520, 385)
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTab = QtWidgets.QTabWidget(About)
        self.mainTab.setObjectName("mainTab")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.about_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.about_tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.mainTab.addTab(self.about_tab, "")
        self.change_history = QtWidgets.QWidget()
        self.change_history.setObjectName("change_history")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.change_history)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputGpkgFile = QgsFileWidget(self.change_history)
        self.inputGpkgFile.setObjectName("inputGpkgFile")
        self.verticalLayout_2.addWidget(self.inputGpkgFile)
        self.changeHistoryTable = QtWidgets.QTableWidget(self.change_history)
        self.changeHistoryTable.setObjectName("changeHistoryTable")
        self.changeHistoryTable.setColumnCount(7)
        self.changeHistoryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.changeHistoryTable.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.changeHistoryTable)
        self.label_2 = QtWidgets.QLabel(self.change_history)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.mainTab.addTab(self.change_history, "")
        self.gridLayout.addWidget(self.mainTab, 0, 0, 1, 1)

        self.retranslateUi(About)
        self.mainTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "QGIS Tracking Changes"))
        self.label.setText(_translate("About", "<html><head/><body><p><span style=\" font-weight:600;\">QGIS Track Changes</span><br/>Version: 0.4.0<br/><br/>This plugin helps track changes in vector layer data, including:<br/>- Feature modifications<br/>- Geometry updates<br/>- Attribute changes<br/><br/>It ensures data integrity by logging changes efficiently within QGIS.<br/><br/><span style=\" font-weight:600;\">Developer:</span> Ahmad Zaenun Faiz<br/><span style=\" font-weight:600;\">License:</span> GPL-3.0<br/><br/>For documentation, visit:<br/><a href=\"https://qgis-track-changes.readthedocs.io/en/latest/\"><span style=\" text-decoration: underline; color:#419cff;\">QGIS Track Changes Documentation</span></a></p></body></html>"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.about_tab), _translate("About", "About"))
        item = self.changeHistoryTable.horizontalHeaderItem(0)
        item.setText(_translate("About", "Last Modified"))
        item = self.changeHistoryTable.horizontalHeaderItem(1)
        item.setText(_translate("About", "Version"))
        item = self.changeHistoryTable.horizontalHeaderItem(2)
        item.setText(_translate("About", "Author"))
        item = self.changeHistoryTable.horizontalHeaderItem(3)
        item.setText(_translate("About", "Layer"))
        item = self.changeHistoryTable.horizontalHeaderItem(4)
        item.setText(_translate("About", "Feature ID"))
        item = self.changeHistoryTable.horizontalHeaderItem(5)
        item.setText(_translate("About", "Message"))
        item = self.changeHistoryTable.horizontalHeaderItem(6)
        item.setText(_translate("About", "Data"))
        self.label_2.setText(_translate("About", "NOTE: currently only works for GeoPackage logger"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.change_history), _translate("About", "Change History"))
from qgsfilewidget import QgsFileWidget
