# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_changes/ui/main_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetupTrackingChanges(object):
    def setupUi(self, SetupTrackingChanges):
        SetupTrackingChanges.setObjectName("SetupTrackingChanges")
        SetupTrackingChanges.resize(451, 310)
        self.gridLayout = QtWidgets.QGridLayout(SetupTrackingChanges)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SetupTrackingChanges)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mQgsLogFile = gui.QgsFileWidget(SetupTrackingChanges)
        self.mQgsLogFile.setObjectName("mQgsLogFile")
        self.verticalLayout.addWidget(self.mQgsLogFile)
        self.label_2 = QtWidgets.QLabel(SetupTrackingChanges)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbVectorLayers = QtWidgets.QComboBox(SetupTrackingChanges)
        self.cbVectorLayers.setObjectName("cbVectorLayers")
        self.horizontalLayout_3.addWidget(self.cbVectorLayers)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbActivate = QtWidgets.QPushButton(SetupTrackingChanges)
        self.pbActivate.setObjectName("pbActivate")
        self.horizontalLayout_2.addWidget(self.pbActivate)
        self.pbDeactivate = QtWidgets.QPushButton(SetupTrackingChanges)
        self.pbDeactivate.setObjectName("pbDeactivate")
        self.horizontalLayout_2.addWidget(self.pbDeactivate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(17, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetupTrackingChanges)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SetupTrackingChanges)
        self.buttonBox.accepted.connect(SetupTrackingChanges.accept)
        self.buttonBox.rejected.connect(SetupTrackingChanges.reject)
        QtCore.QMetaObject.connectSlotsByName(SetupTrackingChanges)

    def retranslateUi(self, SetupTrackingChanges):
        _translate = QtCore.QCoreApplication.translate
        SetupTrackingChanges.setWindowTitle(_translate("SetupTrackingChanges", "Setup Tracking Changes"))
        self.label.setText(_translate("SetupTrackingChanges", "Log file destination"))
        self.label_2.setText(_translate("SetupTrackingChanges", "Start/stop tracking changes"))
        self.pbActivate.setText(_translate("SetupTrackingChanges", "Activate"))
        self.pbDeactivate.setText(_translate("SetupTrackingChanges", "Deactivate"))
from qgis import gui
