name: Release

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            python -m semantic_release version
          else
            python -m semantic_release version --prerelease
          fi

      - name: Update metadata.txt
        run: python -m metadata_versioning
  
      - name: Commit updated metadata.txt
        run: |
          git add track_changes/metadata.txt
          git commit -m "chore: update metadata.txt with new version" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
