name: Release

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Run Semantic Release on main
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: python -m semantic_release version

      - name: Create RC tag on feature branches
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(python -m semantic_release version --print)
          RC_VERSION="${VERSION}-rc.1"
          
          git tag -a "v${RC_VERSION}" -m "Release candidate ${RC_VERSION}"
          git push origin "v${RC_VERSION}"

      - name: Update metadata.txt
        if: github.ref == 'refs/heads/main'
        run: python -m metadata_versioning
  
      - name: Commit updated metadata.txt
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git add track_changes/metadata.txt
          git commit -m "chore: update metadata.txt with new version" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
